seed: 42
device: "cpu"            
data:
  train_dir: "data/train"
  val_dir: "data/val"
  img_size: 128           
train:
  batch_size: 32
  epochs: 70
  lr: 0.0001
  weight_decay: 0.0001
  pos_weight: null        
  early_stopping_patience: 8
  ckpt_dir: "checkpoints"
model:
  name: "cnn"         
  in_channels: 3